# Generated by Django 6.0.4 on 2026-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0008_alter_profile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timeloss',
            field=models.BooleanField(default=False),
        ),
    ]
